V2.1.1 amadeus 3286 accommodation target groups
OTDS-eV/OTDS pull request #167
Opened 2020-09-14 08:02 UTC by StNicklaus

I added the new AccommodationTargetgroups and adjusted the general description of AccommodationTargetgroups a bit.
I left open the detailed description of the new targetgroups, because Steffi wanted to do that later on.

2020-09-14 09:40 UTC, barkeeper42 approved these changes
OK, thank you.

2020-09-14 16:17 UTC, MarcoSchwanke requested changes
Wir sollten bei den neuen Properties "Traveler" auch mit einem "l" schreiben.

2020-09-16 18:17 UTC, MarcoSchwanke requested changes
Im DocBook stehen die Travellers noch mit doppel L

2020-09-17 11:30 UTC, MarcoSchwanke approved these changes

2020-09-22 07:06 UTC, muskewitz approved these changes

2020-09-22 09:54 UTC, merged