V1.9.4 amadeus
OTDS-eV/OTDS pull request #168
Opened 2020-09-14 09:32 UTC by StNicklaus

Integrated V2.1.1 features and selected V2.0 features

2020-09-14 09:39 UTC, barkeeper42 approved these changes
OK, thank you.

2020-09-14 16:44 UTC, MarcoSchwanke requested changes
Es gibt noch ein paar Stellen mit Copy&Paste Fehlern bei denen noch die OTDS Version auf 2.0 steht.

internal:otdsversion="2.0"

2020-09-16 18:19 UTC, MarcoSchwanke approved these changes

2020-09-22 07:03 UTC, muskewitz approved these changes

2021-03-30 15:19 UTC, OTDSeV approved these changes

2021-03-30 15:51 UTC, StNicklaus commented
CONFIDENTIAL & RESTRICTED

Wer sollte den denn dort eintragen?
Ich?

From: OTDS e.V. ***@***.***>
Sent: Dienstag, 30. März 2021 17:16
To: OTDS-eV/OTDS ***@***.***>
Cc: Stephan NICKLAUS ***@***.***>; Author ***@***.***>
Subject: Re: [OTDS-eV/OTDS] V1.9.4 amadeus (#168)

CAUTION: External mail. Be careful with links and attachments.


Hi Stephan, danke für die 1.9.5.
Ich frage mich, ob der Hinweis auf das SellingUnit Limit von 100 in den Annotations drin ist? (#3367)

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOTDS-eV%2FOTDS%2Fpull%2F168%23issuecomment-810346230&data=04%7C01%7C%7C9ac699dba4ab4164907e08d8f38eca66%7Cb3f4f7c272ce4192aba4d6c7719b5766%7C0%7C0%7C637527141903108887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kITX6KrGSyaVezFvglv4S3H1H1W5jFwrho8%2BdLqDK9k%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFTCTE3TFFHXP67QA5I6J4TTGHTMTANCNFSM4RLL4NTQ&data=04%7C01%7C%7C9ac699dba4ab4164907e08d8f38eca66%7Cb3f4f7c272ce4192aba4d6c7719b5766%7C0%7C0%7C637527141903118885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LEcw3ReN32x9pEZp8f%2BOxkfdeNN5mlziOHVjrACO2lU%3D&reserved=0>.

2021-03-31 08:26 UTC, OTDSeV commented
Ich kann das auch machen; das Limit ist ja sicherlich auch in der 1.9.5 sinnvoll.
Ich hatte angenommen, dass du alle Branches, die auch in die 1.9.5 sollen, dort reingenommen hast irgendwie, jedenfalls hab ich sie in den Commits wiedergefunden - nur eben nicht das Limit...

Ruf mich doch mal kurz an, wenn du Zeit hast, dann können wir das schnell klären...


Danke und VG
Steffi

Am 30.03.2021 um 17:51 schrieb StNicklaus ***@***.***>:




﻿

CONFIDENTIAL & RESTRICTED

Wer sollte den denn dort eintragen?
Ich?

From: OTDS e.V. ***@***.***>
Sent: Dienstag, 30. März 2021 17:16
To: OTDS-eV/OTDS ***@***.***>
Cc: Stephan NICKLAUS ***@***.***>; Author ***@***.***>
Subject: Re: [OTDS-eV/OTDS] V1.9.4 amadeus (#168)

CAUTION: External mail. Be careful with links and attachments.


Hi Stephan, danke für die 1.9.5.
Ich frage mich, ob der Hinweis auf das SellingUnit Limit von 100 in den Annotations drin ist? (#3367)

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOTDS-eV%2FOTDS%2Fpull%2F168%23issuecomment-810346230&data=04%7C01%7C%7C9ac699dba4ab4164907e08d8f38eca66%7Cb3f4f7c272ce4192aba4d6c7719b5766%7C0%7C0%7C637527141903108887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kITX6KrGSyaVezFvglv4S3H1H1W5jFwrho8%2BdLqDK9k%3D&reserved=0>,
 or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFTCTE3TFFHXP67QA5I6J4TTGHTMTANCNFSM4RLL4NTQ&data=04%7C01%7C%7C9ac699dba4ab4164907e08d8f38eca66%7Cb3f4f7c272ce4192aba4d6c7719b5766%7C0%7C0%7C637527141903118885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LEcw3ReN32x9pEZp8f%2BOxkfdeNN5mlziOHVjrACO2lU%3D&reserved=0>.
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

2021-03-31 13:11 UTC, closed without merging