Added UnitFacilities
OTDS-eV/OTDS pull request #203
Opened 2022-07-20 13:29 UTC by jpolifka

UnitFacilities PrivateToilette and DirectSharedPoolAccess

2022-07-20 15:31 UTC, matthiasz-schmetterling approved these changes

2022-08-03 14:25 UTC, StNicklaus approved these changes

2022-08-26 08:53 UTC, MarcoSchwanke requested changes
Neue Enum Werte bitte am Ende anfügen. Es gibt Systeme die arbeiten mit der Nummerierung der Enums und nicht den Enum Namen

2022-08-26 08:55 UTC, MarcoSchwanke requested changes
Neue Enum Werte am Ende anfügen

2022-08-30 14:25 UTC, muskewitz approved these changes

2022-09-13 12:46 UTC, OTDSeV approved these changes

2022-09-13 13:35 UTC, merged