Ticket 3785 Kapitel 3 DocBook
OTDS-eV/OTDS pull request #215
Opened 2023-09-22 16:44 UTC by jpolifka

2023-09-25 10:11 UTC, OTDSeV commented on doku/spec/otds_spezifikation.docbook
> +									<para xml:id="en_010045" xml:lang="en">Defined in version</para>
macht das was, dass hier die Reihenfolge des deutschen/englischen Spaltenkopfes vertauscht ist?

2023-09-25 10:13 UTC, OTDSeV commented on doku/spec/otds_spezifikation.docbook
> +									<para xml:id="de_010049" xml:lang="de">BookonOption</para>
Wir hatten "on" bisher immer mit großem O geschrieben: BookOnOption

2023-09-25 10:15 UTC, OTDSeV approved these changes
Was soll mit "standardisiert in Version" ausgedrückt werden? Dass die PreVersionProperty zur normalen Property wurde?

2023-09-25 10:25 UTC, jpolifka commented
> Was soll mit "standardisiert in Version" ausgedrückt werden? Dass die PreVersionProperty zur normalen Property wurde?

Ich vermute, es wird eine Übergangsphase geben, in der sowohl die PreVersionProperty als auch die in den Standard aufgenommene Version genutzt wird. Dazu sollten wir ausweisen können, wann die PreVersionProperty aufgenommen, in den Standard überführt und ab wann sie nicht mehr genutzt werden darf.

2023-09-25 10:31 UTC, jpolifka commented on doku/spec/otds_spezifikation.docbook
> +									<para xml:id="en_010045" xml:lang="en">Defined in version</para>
Reihenfolge korrekt angepasst

2023-09-26 12:37 UTC, matthiasz-schmetterling approved these changes

2023-09-26 14:30 UTC, StNicklaus requested changes
Hi Jens, 
es gibt m.E. nur ein BookOnOption für ein Angebot. Deshlab finde ich die Formulierung "Definiert, dass diese Komponente als Option buchbar ist" falsch.
Es gibt keine Properties, die sich auf Komponenenten unterschiedlich ausprägen. 
Es müsste m.E. deshlab besser heißen:
"Definiert, ob ein Angebot als Option buchbar ist."
Das hat aber nichts damit zu tun, dass die Komponenten mit Tags und Bedingungen durchaus Einfluss auf die Auswertung der Property nehmen können.

2023-09-26 14:35 UTC, jpolifka commented
> Hi Jens,
> es gibt m.E. nur ein BookOnOption für ein Angebot. Deshlab finde ich die Formulierung "Definiert, dass diese Komponente als Option buchbar ist" falsch.
> Es gibt keine Properties, die sich auf Komponenenten unterschiedlich ausprägen.
> Es müsste m.E. deshlab besser heißen:
> "Definiert, ob ein Angebot als Option buchbar ist."
> Das hat aber nichts damit zu tun, dass die Komponenten mit Tags und Bedingungen durchaus Einfluss auf die Auswertung der Property nehmen können.

Hi Stephan,

das ist tatsächlich Definitionssache - erst das Zusammenspiel beider Komponenten Flug + Hotel definiert, ob das gesamte Angebot als Option buchbar ist. 
Daher bezog sich die PreVersionProperty nur auf die jeweilige Komponente. 
Aus dem Hotel heraus kann ich bei BookOnOption=J erstmal nicht sagen, ob das gesamte Pauschalangebot als Option buchbar ist. 

In der Formulierung können wir das gerne etwas softer gestalten. 

Viele Grüße
Jens

2023-09-26 14:53 UTC, StNicklaus commented
CONFIDENTIAL & RESTRICTED

Hi Jens,
Wie bereits erwähnt.
Die Property steht für das gesamte Angebot.
Das die Property dann über die Auswertungen einzelner Tags an den Komponetnen zur Gültigkeit kommt ist Teil der Bedingungsauswertung.
Die Property wird ausgewertet und am Ende ist sie gültig oder nicht. Dabei werden keine einzelnen Komponenten betrachtet.

Wenn wir hier etwas komponentenbezogenes einführen wollen, dann fehlt die formale Festlegung, wie man Properties  einer Komponente zuordnet und ebenfalls wie man dann zu einem Status der Property bezogen auf das gesamte Angebot kommt.
Zusätzlich muss man noch darüber nachdenken, ob die Property auch noch auf Unit, SellingUnit, Board und BookingClass bezogen werden muss, denn das sind formal auch Komponenten.
Ich würde gerne vermeiden, dass wir dieses Fass aufmachen.

Viele Grüße
Stephan


Von: Jens Polifka ***@***.***>
Gesendet: Dienstag, 26. September 2023 16:35
An: OTDS-eV/OTDS ***@***.***>
Cc: Stephan NICKLAUS ***@***.***>; Review requested ***@***.***>
Betreff: Re: [OTDS-eV/OTDS] Ticket 3785 Kapitel 3 DocBook (PR #215)

EXTERNAL Email. Be careful with links and attachments! If in doubt, click the Report Mail button.


Hi Jens,
es gibt m.E. nur ein BookOnOption für ein Angebot. Deshlab finde ich die Formulierung "Definiert, dass diese Komponente als Option buchbar ist" falsch.
Es gibt keine Properties, die sich auf Komponenenten unterschiedlich ausprägen.
Es müsste m.E. deshlab besser heißen:
"Definiert, ob ein Angebot als Option buchbar ist."
Das hat aber nichts damit zu tun, dass die Komponenten mit Tags und Bedingungen durchaus Einfluss auf die Auswertung der Property nehmen können.

Hi Stephan,

das ist tatsächlich Definitionssache - erst das Zusammenspiel beider Komponenten Flug + Hotel definiert, ob das gesamte Angebot als Option buchbar ist.
Daher bezog sich die PreVersionProperty nur auf die jeweilige Komponente.
Aus dem Hotel heraus kann ich bei BookOnOption=J erstmal nicht sagen, ob das gesamte Pauschalangebot als Option buchbar ist.

In der Formulierung können wir das gerne etwas softer gestalten.

Viele Grüße
Jens

-
Reply to this email directly, view it on GitHub<https://github.com/OTDS-eV/OTDS/pull/215#issuecomment-1735674667>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AFTCTE5LKLYP7OTA26XVSW3X4LR23ANCNFSM6AAAAAA5DLWRSU>.
You are receiving this because your review was requested.Message ID: ***@***.******@***.***>>

2023-09-27 11:26 UTC, muskewitz approved these changes

2023-11-09 17:36 UTC, StNicklaus approved these changes

2023-11-09 19:04 UTC, merged